import Link from "next/link";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import Reveal from "@/components/Reveal";
import Story from "@/components/Story";
import Visual from "@/components/Visual";
import { site } from "@/lib/site";

export default function Home(){
 const schema={"@context":"https://schema.org","@type":site.businessType,"name":site.name,"url":site.url,"description":"Proyecto, obra y acabados coordinados en un único proceso. Reformas integrales de viviendas, cocinas y baños con planificación clara y atención al detalle.","areaServed":site.city,"makesOffer":site.services.map(s=>({"@type":"Offer","itemOffered":{"@type":"Service","name":s.title}}))};
 return <><NavBar/><main>
 <section className="hero"><div className="hero-orb"/><div className="shell hero-grid"><div className="hero-copy"><p className="eyebrow">REFORMAS INTEGRALES · MADRID</p><h1>Tu casa, rediseñada desde dentro.</h1><p className="lead">Proyecto, obra y acabados coordinados en un único proceso. Reformas integrales de viviendas, cocinas y baños con planificación clara y atención al detalle.</p><div className="hero-actions"><Link className="button primary" href="/contacto">Cuéntanos tu reforma</Link><Link className="button ghost" href="#servicios">Ver servicios</Link></div></div><div className="hero-art"><Visual stage={0}/></div></div><div className="shell stats"><div><strong>01</strong><span>Equipo coordinado</span></div><div><strong>02</strong><span>Proyecto y ejecución</span></div><div><strong>03</strong><span>Seguimiento de obra</span></div></div></section>
 <section id="servicios" className="section shell"><Reveal><p className="eyebrow">SERVICIOS</p><h2 className="display">Contenido útil para usuarios y buscadores.</h2><p className="section-intro">Cada servicio dispone de su propia URL, encabezado principal, texto especializado, metadatos y enlazado interno. La estructura está pensada para crecer con nuevas zonas o servicios.</p></Reveal><div className="service-grid"><Link href="/servicios/reformas-integrales" className="service-card"><span>01</span><h3>Reformas integrales en Madrid</h3><p>Coordinamos la reforma completa de pisos y viviendas: distribución, instalaciones, albañilería, revestimientos, pintura, carpintería e iluminación.</p><b>Ver servicio →</b></Link><Link href="/servicios/reformas-cocinas" className="service-card"><span>02</span><h3>Reformas de cocinas en Madrid</h3><p>Diseñamos cocinas funcionales, luminosas y pensadas para el uso diario, desde instalaciones hasta mobiliario y acabados.</p><b>Ver servicio →</b></Link><Link href="/servicios/reformas-banos" className="service-card"><span>03</span><h3>Reformas de baños en Madrid</h3><p>Actualizamos baños con nuevas instalaciones, impermeabilización, revestimientos, iluminación y soluciones de almacenaje.</p><b>Ver servicio →</b></Link></div></section>
 <Story/>
 <section className="section shell"><div className="split-title"><p className="eyebrow">POSICIONAMIENTO ORGÁNICO</p><h2>SEO que empieza por explicar bien el servicio.</h2></div><div className="seo-grid"><Reveal className="seo-card"><h3>Reformas con una planificación realista</h3><p>Cada vivienda parte de una situación diferente. Antes de presupuestar con detalle conviene definir alcance, necesidades y prioridades. Esto permite ordenar las partidas de obra, prever decisiones de materiales y reducir cambios durante la ejecución.</p></Reveal><Reveal className="seo-card"><h3>Un único criterio para toda la vivienda</h3><p>Cuando distribución, instalaciones y acabados se plantean en conjunto, el resultado es más coherente. La iluminación, las carpinterías y los revestimientos dejan de ser decisiones aisladas y pasan a formar parte de un mismo proyecto.</p></Reveal></div></section>
 <section className="cta-band"><div className="shell"><p className="eyebrow">MADRID</p><h2>Reformas integrales pensadas para vivir mejor.</h2><p>La ubicación, la marca y los datos de contacto están centralizados para que puedas adaptar esta plantilla a un proyecto real.</p><Link className="button light" href="/contacto">Solicitar información</Link></div></section>
 </main><Footer/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/></>
}
