"use client";
import { motion, MotionValue, useScroll, useSpring, useTransform } from "framer-motion";
import { useRef } from "react";
const steps=[
 {n:"01",k:"Lectura",t:"Medimos la vivienda, detectamos condicionantes y convertimos necesidades en prioridades."},
 {n:"02",k:"Plano",t:"La distribución se decide antes que los acabados: recorridos, luz, almacenaje y proporciones."},
 {n:"03",k:"Vacío",t:"La demolición deja visible el espacio real y prepara el soporte para la nueva organización."},
 {n:"04",k:"Infraestructura",t:"Electricidad, fontanería y climatización se coordinan antes de cerrar paredes y techos."},
 {n:"05",k:"Materia",t:"Revestimientos, madera, pintura e iluminación empiezan a construir la atmósfera final."},
 {n:"06",k:"Habitar",t:"Remates, pruebas y una última revisión convierten la obra en una vivienda lista para usarse."}
];
function Step({s,i,p}:{s:(typeof steps)[number];i:number;p:MotionValue<number>}){const a=i/steps.length,b=(i+.5)/steps.length,c=(i+1)/steps.length;const opacity=useTransform(p,[a,b,c],[.12,1,.12]);const x=useTransform(p,[a,b,c],[24,0,-18]);return <motion.div className="story-step" style={{opacity,x}}><span>{s.n}</span><div><h3>{s.k}</h3><p>{s.t}</p></div></motion.div>}
export default function Story(){const ref=useRef<HTMLElement>(null);const {scrollYProgress}=useScroll({target:ref,offset:["start start","end end"]});const p=useSpring(scrollYProgress,{stiffness:75,damping:25,mass:.28});const plan=useTransform(p,[0,.18,.38],[1,1,0]);const wall=useTransform(p,[.18,.42],[0,1]);const services=useTransform(p,[.34,.60],[0,1]);const finish=useTransform(p,[.56,.84],[0,1]);const furniture=useTransform(p,[.76,1],[0,1]);const rotate=useTransform(p,[0,1],[-3,1]);const bar=useTransform(p,[0,1],["0%","100%"]);const furnitureY=useTransform(furniture,[0,1],[22,0]);const furnitureScale=useTransform(furniture,[0,1],[.5,1]);return <section ref={ref} id="story" className="story-wrap reform-story"><div className="story-sticky shell"><div className="story-copy"><p className="eyebrow">SCROLL 01 · EL PROCESO</p><h2>De plano a hogar, sin saltarse ninguna capa.</h2><div className="story-steps">{steps.map((s,i)=><Step key={s.n} s={s} i={i} p={p}/>)}</div></div><motion.div className="story-visual" style={{rotate}}><div className="plan-scene"><motion.div className="plan-paper" style={{opacity:plan}}><i/><i/><i/><span>PLANTA 01</span></motion.div><motion.div className="build-wall w1" style={{scaleY:wall}}/><motion.div className="build-wall w2" style={{scaleX:wall}}/><motion.div className="service-lines" style={{opacity:services}}><i/><i/><i/></motion.div><motion.div className="finish-plane" style={{opacity:finish}}/><motion.div className="furniture f-sofa" style={{opacity:furniture,y:furnitureY}}/><motion.div className="furniture f-table" style={{opacity:furniture,scale:furnitureScale}}/><div className="scene-label">NOVA / PROJECT 24</div></div></motion.div><div className="story-progress"><motion.i style={{width:bar}}/></div></div></section>}
